extends Node

var lang: String = "en"

const _strings: Dictionary = {
	"en": {
		"game_subtitle":     "Sneaky Futures Trading",
		"menu_start":        "Start Game",
		"menu_options":      "Options",
		"menu_quit":         "Quit",
		"opt_back":          "Back",
		"opt_language":      "Language: %s",
		"opt_bgm":           "Music: [%s] %d%%",
		"opt_sfx":           "Sound: [%s] %d%%",
		"lang_name":         "English",
		"menu_stage_select":  "Stage Select",
		"ss_title":          "— Stage Select —",
		"ss_stage":          "Stage %d",
		"hint_stage_select": "[W/S] Navigate   [Z] Select   [X] Back",
		"hint_main":         "[W/S] Navigate   [Z] Select",
		"hint_options":      "[W/S] Navigate   [←/→] Adjust   [Z] Select   [X] Back",
		"result_win":        "VICTORY!",
		"result_win_sub":    "You cleared the target. Honey never knew!",
		"result_lose":       "FAILED",
		"result_short":      "Short by $%.0f",
		"result_amount":     "Realized: $%.2f / $%.0f",
		"result_hint":       "[Z] Play Again   [X] Lobby",
		"go_title":          "Game Over",
		"go_caught":         "Your honey saw the screen!",
		"go_timeout":        "Time's up — target not reached.",
		"go_suspicion":      "Suspicion gauge depleted!",
		"go_final":          "Final: $%.0f / $%.0f",
		"go_hint":           "[Z] Try Again   [X] Lobby",
		"cs_0":              "A quiet Sunday afternoon at home...",
		"cs_1":              "I saw you checking your phone again...",
		"cs_2":              "If I catch you trading again, you're DONE!",
		"cs_3":              "(Nods obediently)",
		"cs_4":              "(But deep down... the charts are calling...)",
		"cs_hint":           "[Z / X] Next",
		"sp_honey":           "Honey",
		"sp_husb":           "Husband",
		"hud_bal":           "Bal $%.0f",
		"phone_no_pos":      "No open positions",
		"phone_pnl":         "P&L %s$%.0f",
		"lc_confirm":        "Confirm Order",
		"lc_add_share":      "Add 1 Share (%d/%d)",
		"lc_back":           "Back",
		"lc_direction":      "Direction: %s",
		"lc_price":          "Price:  $%.2f",
		"lc_cost":           "Cost:   $%.2f",
		"dir_long":          "LONG",
		"dir_short":         "SHORT",
		"dir_long_btn":      "Long",
		"dir_short_btn":     "Short",
		"trend_up":          "Up",
		"trend_down":        "Down",
		"chart_hint_pos":    "Pos: %s x%d  P&L: $%.2f (%.1f%%)  [Z]Order [X]Back",
		"chart_hint_no_pos": "[Z]Select Direction → Confirm  [X]Back",
		"chart_high_vol":    "High Vol  Trend: %s  Rev: %.0f%%",
		"ls_header":         " Name          Price     Pos       P&L%    Action",
		"ls_hint":           "[Z]Ent [C]Cls",
		"pause_title":       "— PAUSE —",
		"pause_resume":      "Continue",
		"pause_quit":        "Quit to Lobby",
		"pause_hint":        "[W/S] Select  [Z] Confirm  [ESC] Continue",
		"qte_title":         "QTE — Press keys in order!",
		"hint_stage1":       "Stage 1 — Home   [Space] Hide Phone   [Z] Confirm   [X] Cancel   [W/S] Navigate   [C] Close Position",
		"hint_stage2":       "Stage 2 — Shopping Street   [Space] Hide Phone   Honey appears at random positions!",
		"hint_stage3":       "Stage 3 — Date Spot   [Space] Hide   [I/O/J/K] QTE   Suspicion gauge active!",
	},
	"zh": {
		"game_subtitle":     "偷偷期貨交易",
		"menu_start":        "開始遊戲",
		"menu_options":      "設定",
		"menu_quit":         "退出",
		"opt_back":          "返回",
		"opt_language":      "語言: %s",
		"opt_bgm":           "背景音樂: [%s] %d%%",
		"opt_sfx":           "音效音量: [%s] %d%%",
		"lang_name":         "中文",
		"menu_stage_select":  "選關卡",
		"ss_title":          "— 選擇關卡 —",
		"ss_stage":          "第 %d 關",
		"hint_stage_select": "[W/S] 移動   [Z] 選擇   [X] 返回",
		"hint_main":         "[W/S] 移動   [Z] 選擇",
		"hint_options":      "[W/S] 移動   [←/→] 調整   [Z] 選擇   [X] 返回",
		"result_win":        "勝利！",
		"result_win_sub":    "達成目標！老婆完全不知情！",
		"result_lose":       "失敗",
		"result_short":      "不足 $%.0f",
		"result_amount":     "已實現: $%.2f / $%.0f",
		"result_hint":       "[Z] 再玩一次   [X] 大廳",
		"go_title":          "遊戲結束",
		"go_caught":         "老婆看到螢幕了！",
		"go_timeout":        "時間到 — 未達目標",
		"go_suspicion":      "懷疑值耗盡！",
		"go_final":          "最終: $%.0f / $%.0f",
		"go_hint":           "[Z] 再試一次   [X] 大廳",
		"cs_0":              "平靜的週日午後...",
		"cs_1":              "我看到你又在玩手機了...",
		"cs_2":              "再讓我抓到你在交易，你就完了！",
		"cs_3":              "（乖巧地點頭）",
		"cs_4":              "（但內心深處... K線在呼喚...）",
		"cs_hint":           "[Z / X] 下一頁",
		"sp_honey":           "老婆",
		"sp_husb":           "老公",
		"hud_bal":           "餘額 $%.0f",
		"phone_no_pos":      "無持倉",
		"phone_pnl":         "損益 %s$%.0f",
		"lc_confirm":        "確認下單",
		"lc_add_share":      "加碼 1 股 (%d/%d)",
		"lc_back":           "返回",
		"lc_direction":      "方向: %s",
		"lc_price":          "價格:  $%.2f",
		"lc_cost":           "成本:   $%.2f",
		"dir_long":          "多頭",
		"dir_short":         "空頭",
		"dir_long_btn":      "做多",
		"dir_short_btn":     "做空",
		"trend_up":          "漲",
		"trend_down":        "跌",
		"chart_hint_pos":    "持倉: %s x%d  損益: $%.2f (%.1f%%)  [Z]下單 [X]返回",
		"chart_hint_no_pos": "[Z]選擇方向 → 確認  [X]返回",
		"chart_high_vol":    "高波動  趨勢: %s  反轉: %.0f%%",
		"ls_header":         " 名稱          價格     持倉       損益%    操作",
		"ls_hint":           "[Z]進 [C]出",
		"pause_title":       "— 暫停 —",
		"pause_resume":      "繼續遊戲",
		"pause_quit":        "退出到大廳",
		"pause_hint":        "[W/S] 選擇  [Z] 確認  [ESC] 繼續",
		"qte_title":         "QTE — 依序按鍵！",
		"hint_stage1":       "第一關 — 家中   [Space] 藏手機   [Z] 確認   [X] 取消   [W/S] 移動   [C] 平倉",
		"hint_stage2":       "第二關 — 購物街   [Space] 藏手機   Honey 會隨機出現！",
		"hint_stage3":       "第三關 — 約會地點   [Space] 藏手機   [I/O/J/K] QTE   懷疑值進行中！",
	}
}


func t(key: String) -> String:
	var dict: Dictionary = _strings.get(lang, _strings["en"])
	return dict.get(key, _strings["en"].get(key, key))


func set_lang(l: String) -> void:
	lang = l
